export const LOGIN = '/api/auth/validatelogin'
export const GETKEY = 'api/auth/getpublickey'
export const ADMINPORTAL = '/web/adminportal'
export const REGISTER = '/api/auth/register'
export const VALIDATETOKEN = '/api/auth/validatetoken'
